### ISSUE TITLE
the device not support peripheral

### ISSUE THREAD

**Issue by chentianci123** [charlesgrant/BeaconMock#1]
mBluetoothAdvertiser = mBluetoothAdapter.getBluetoothLeAdvertiser();
        if (mBluetoothAdvertiser == null) {
            Toast.makeText(activity, "the device not support peripheral", Toast.LENGTH_SHORT).show();
            Log.e(TAG, "the device not support peripheral");
            activity.finish();
            return;
        }

在初始化的时候，打印这句话，说明我的手机不支持外围设备，请问该怎么解决？

**Comment by chentianci123** [comment]
我找到原因了，是因为我的蓝牙没有打开导致的，但是又出现了问题，就是我在开启广播的成功和失败回调函数中都进行了打印，都没有打印，你遇到过这个问题吗

**Comment by chentianci123** [comment]
我已经回调成功了，请问如何检测或者搜索广播？

**Comment by chentianci123** [comment]
他是否可以设置蓝牙可被搜索到或者公开的（public），我的回调函数说明我广播成功了，但是搜索不到我的广播

**Comment by zhanggonglin** [comment]
有没有开启定位权限


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chentianci123"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 上午10:03
收件人:&nbsp;"charlesgrant/BeaconMock"<BeaconMock@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [charlesgrant/BeaconMock] the device not support peripheral (#1)




我找到原因了，是因为我的蓝牙没有打开导致的，但是又出现了问题，就是我在开启广播的成功和失败回调函数中都进行了打印，都没有打印，你遇到过这个问题吗

**Comment by chentianci123** [comment]
我解决了这个问题 是因为我搜索时进行了过滤 现在已经好了，非常感谢
